services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
      MYSQL_DATABASE: database
